export const titleRow: string;
export const inputRow: string;
export const align: string;
export const directionIcon: string;
export const iconLeft: string;
export const iconRight: string;
export const textField: string;
export const switchIcon: string;
export const box: string;